require_relative 'server_launcher'

desc 'Running Android tests!'
task :android, :type do |t, args|
  task_setup android_app, args
end

def task_setup app, args
  types = ['single', 'dist', 'parallel']
  unless types.include? args[:type]
    puts "Invalid run type!\nChoose: #{types}"
    abort
  end

  ENV["PROJECT_DIR"] = Dir.pwd
  ENV["APP_PATH"] = app

  ENV['SAUCE_USERNAME'] = nil
  ENV['SAUCE_ACCESS_KEY'] = nil

  if ['dist', 'parallel'].include? args[:type]
    threads = "-n #{ENV["THREADS"]}"
    ENV["SERVER_URL"] = "http://localhost:4444/wd/hub" #Change this to your hub url if different.
  end

  case args[:type]
  when "single"
    exec "rspec spec #{tag}"
  when "dist"
    exec "parallel_rspec #{threads} spec"
  when "parallel"
    exec "parallel_test #{threads} -e 'rspec spec #{tag}'"
  end
end

def android_app
  "#{Dir.pwd}/spec/app-debug.apk"
end

def upload_app_to_sauce app
  require 'sauce_whisk'
  storage = SauceWhisk::Storage.new
  puts "Uploading #{app} to saucelabs...\n"
  storage.upload app
  ENV["APP_PATH"] = "sauce-storage:#{File.basename(app)}"
end