require_relative 'server_launcher'


desc 'Running Android tests!'
task :android, :type do |t, args|
  task_setup args
end

def task_setup args
  types = ['single', 'dist', 'parallel', 'sauce']
  unless types.include? args[:type]
    puts "Invalid run type!\nChoose: #{types}"
    abort
  end
  
  setup_output_dir

  ENV["PROJECT_DIR"] = Dir.pwd

  if args[:type] == "single"
    start_single_appium
  elsif ['dist', 'parallel'].include? args[:type]
    launch_hub_and_nodes
    threads = "-n #{ENV["THREADS"]}"
    ENV["SERVER_URL"] = "http://localhost:4444/wd/hub" #Change this to your hub url if different.
  end
  
  if ['single', 'dist', 'parallel'].include? args[:type]
    ENV['SAUCE_USERNAME'], ENV['SAUCE_ACCESS_KEY'] = nil, nil
    ENV["APP_PATH"] = android_app
  end
  
  case args[:type]
  when "single"
    ENV['SAUCE_USERNAME'], ENV['SAUCE_ACCESS_KEY'] = nil, nil
    exec "rspec spec"
  when "dist"
    exec "parallel_rspec #{threads} spec"
  when "parallel"
    exec "parallel_test #{threads} -e 'rspec spec'"
  when "sauce"
    ENV['ENV'] = "sauce"
    ENV["SERVER_URL"] = "http://#{ENV['SAUCE_USERNAME']}:#{ENV['SAUCE_ACCESS_KEY']}@ondemand.saucelabs.com:80/wd/hub"
    upload_app_to_sauce android_app
    exec "parallel_rspec spec"
  end
end

def android_app
  "#{Dir.pwd}/app-debug.apk"
end

def setup_output_dir
  kill_processes
  if OS.mac?
    system "mkdir output >> /dev/null 2>&1"
    `rm ./output/*  >> /dev/null 2>&1`
  elsif OS.windows?
    files = Dir.entries("#{Dir.pwd}/output/").find_all { |f| f if f.include? "log" or f.include? "png" }
    files.each { |f| File.delete "#{Dir.pwd}/output/#{f}" }
  end
end

def upload_app_to_sauce app
  require 'sauce_whisk'
  storage = SauceWhisk::Storage.new
  puts "Uploading #{app} to saucelabs...\n"
  storage.upload app
  ENV["APP_PATH"] = "sauce-storage:#{File.basename(app)}"
end