require_relative 'server_launcher'

desc 'Running Android tests!'
task :android, :type do |t, args|
  task_setup android_app, args
end

def task_setup app, args
  types = ['single', 'dist', 'parallel']
  unless types.include? args[:type]
    puts "Invalid run type!\nChoose: #{types}"
    abort
  end

  setup_output_dir

  ENV["PROJECT_DIR"] = Dir.pwd
  ENV["APP_PATH"] = app

  if args[:type] == "single"
    start_single_appium
  elsif ['dist', 'parallel'].include? args[:type]
    launch_hub_and_nodes
    threads = "-n #{ENV["THREADS"]}"
    ENV["SERVER_URL"] = "http://localhost:4444/wd/hub" #Change this to your hub url if different.
  end

  case args[:type]
  when "single"
    exec "rspec spec"
  when "dist"
    exec "parallel_rspec #{threads} spec"
  when "parallel"
    exec "parallel_test #{threads} -e 'rspec spec'"
  end
end

def android_app
  "#{Dir.pwd}/app-debug.apk"
end

def setup_output_dir
  if OS.mac?
    system "mkdir output >> /dev/null 2>&1"
    `rm ./output/*  >> /dev/null 2>&1`
  elsif OS.windows?
    files = Dir.entries("#{Dir.pwd}/output/").find_all { |f| f if f.include? "log" or f.include? "png" }
    files.each { |f| File.delete "#{Dir.pwd}/output/#{f}" }
  end
end